import { StyleSheet } from "react-native";

export default StyleSheet.create({
  imageBackground: {
    width: "100%",
  },
  imageHeightBackground: {
    width: "100%",
    height: "100%",
  },
  displayFlexDesktop: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-around",
  },
  bodyHomeDesktop: {
    width: 490,
    display: "flex",
    flexDirection: "column",
    marginTop: "10rem",
  },
  bodyHomeTablet: {
    width: 445,
    display: "flex",
    flexDirection: "column",
    margin: "auto",
  },
  textHome: {
    textTransform: "uppercase",
    color: "#D0D6F9",
    textAlign: "center",
    marginTop: "3rem",
    fontFamily: "Barlow_400Regular",
    letterSpacing: 2.7,
    fontSize: 16,
  },
  textHomeTablet: {
    textTransform: "uppercase",
    color: "#D0D6F9",
    marginTop: "3rem",
    marginLeft: "0.7rem",
    fontFamily: "Barlow_400Regular",
    letterSpacing: 3.38,
    fontSize: 20,
  },
  textHomeDesktop: {
    textTransform: "uppercase",
    color: "#D0D6F9",
    marginTop: "3rem",
    fontFamily: "Barlow_400Regular",
    letterSpacing: 4.72,
    fontSize: 28,
  },
  textSpace: {
    textTransform: "uppercase",
    color: "#FEFEFE",
    textAlign: "center",
    marginTop: "1rem",
    fontSize: 72,
    fontFamily: "Bellefair_400Regular",
  },
  textSpaceTablet: {
    textTransform: "uppercase",
    color: "#FEFEFE",
    textAlign: "center",
    marginTop: "1rem",
    fontSize: 150,
    fontFamily: "Bellefair_400Regular",
  },
  textSpaceDesktop: {
    textTransform: "uppercase",
    color: "#FEFEFE",
    marginTop: "1rem",
    fontSize: 150,
    fontFamily: "Bellefair_400Regular",
  },
  textDescription: {
    color: "#D0D6F9",
    textAlign: "center",
    fontSize: 16,
    lineHeight: 24,
    marginLeft: "1.5rem",
    marginRight: "1.5rem",
    marginTop: "1rem",
    fontFamily: "Barlow_400Regular",
  },
  textDescriptionDesktop: {
    color: "#D0D6F9",
    fontSize: 18,
    lineHeight: 32,
    marginRight: "1.5rem",
    marginTop: "1rem",
    fontFamily: "Barlow_400Regular",
  },
  contentPressable: {
    width: 150,
    height: 150,
    backgroundColor: "#FFFFFF",
    borderRadius: 100,
    display: "flex",
    marginVertical: "4rem",
    margin: "auto",
    textAlign: "center",
  },
  contentPressableTablet: {
    width: 200,
    height: 200,
    backgroundColor: "#FFFFFF",
    borderRadius: 100,
    display: "flex",
    marginVertical: "4rem",
    margin: "auto",
    textAlign: "center",
  },
  contentPressableDesktop: {
    width: 274,
    height: 274,
    backgroundColor: "#FFFFFF",
    borderRadius: 200,
    display: "flex",
    marginVertical: "4rem",
    margin: "auto",
    marginTop: "19rem",
    textAlign: "center",
  },
  textPressable: {
    color: "#0B0D17",
    fontSize: 20,
    textTransform: "uppercase",
    fontFamily: "Bellefair_400Regular",
    textAlign: "center",
    marginTop: "4rem",
  },
  textPressableTablet: {
    color: "#0B0D17",
    fontSize: 32,
    textTransform: "uppercase",
    fontFamily: "Bellefair_400Regular",
    textAlign: "center",
    marginTop: "5rem",
  },
  textPressableDesktop: {
    color: "#0B0D17",
    fontSize: 32,
    textTransform: "uppercase",
    fontFamily: "Bellefair_400Regular",
    textAlign: "center",
    marginTop: "7rem",
  },
  circlePulse: {
    width: 400,
    height: 400,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 200,
    position: "absolute",
    zIndex: -1,
    bottom: -60,
    right: -66,
  },
  circlePulseTablet: {
    width: 300,
    height: 300,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 200,
    position: "absolute",
    zIndex: -1,
    bottom: -50,
    right: -50,
  },
  circlePulseMobile: {
    width: 200,
    height: 200,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 200,
    position: "absolute",
    zIndex: -1,
    bottom: -24,
    right: -26,
  },
});
