import { StyleSheet } from "react-native";

export default StyleSheet.create({
  imageBackground: {
    width: "100%",
  },
  bodyHomeTablet: {
    width: 445,
    display: "flex",
    flexDirection: "column",
    margin: "auto",
  },
  textHome: {
    textTransform: "uppercase",
    color: "#D0D6F9",
    textAlign: "center",
    marginTop: "3rem",
    fontFamily: "Barlow_400Regular",
    letterSpacing: 2.7,
    fontSize: 16,
  },
  textHomeTablet: {
    textTransform: "uppercase",
    color: "#D0D6F9",
    marginTop: "3rem",
    marginLeft: "0.7rem",
    fontFamily: "Barlow_400Regular",
    letterSpacing: 3.38,
    fontSize: 20,
  },
  textSpace: {
    textTransform: "uppercase",
    color: "#FEFEFE",
    textAlign: "center",
    marginTop: "1rem",
    fontSize: 72,
    fontFamily: "Bellefair_400Regular",
  },
  textSpaceTablet: {
    textTransform: "uppercase",
    color: "#FEFEFE",
    textAlign: "center",
    marginTop: "1rem",
    fontSize: 150,
    fontFamily: "Bellefair_400Regular",
  },
  textDescription: {
    color: "#D0D6F9",
    textAlign: "center",
    fontSize: 16,
    lineHeight: 24,
    marginLeft: "1.5rem",
    marginRight: "1.5rem",
    marginTop: "1rem",
    fontFamily: "Barlow_400Regular",
  },
  contentPressable: {
    width: 150,
    height: 150,
    backgroundColor: "#FFFFFF",
    borderRadius: 100,
    display: "flex",
    marginVertical: "4rem",
    margin: "auto",
    textAlign: "center",
  },
  contentPressableTablet: {
    width: 200,
    height: 200,
    backgroundColor: "#FFFFFF",
    borderRadius: 100,
    display: "flex",
    marginVertical: "4rem",
    margin: "auto",
    textAlign: "center",
  },
  textPressable: {
    color: "#0B0D17",
    fontSize: 20,
    textTransform: "uppercase",
    fontFamily: "Bellefair_400Regular",
    textAlign: "center",
    marginTop: "4rem",
  },
  textPressableTablet: {
    color: "#0B0D17",
    fontSize: 32,
    textTransform: "uppercase",
    fontFamily: "Bellefair_400Regular",
    textAlign: "center",
    marginTop: "5rem",
  },
});
